package com.neusoft.domain;

public class Address {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.addressid
     *
     * @mbg.generated Sat Jul 28 09:38:49 CST 2018
     */
    private Integer addressid;

    /* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.userid
     *
     * @mbg.generated Sat Jul 28 09:38:49 CST 2018
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.province
     *
     * @mbg.generated Sat Jul 28 09:38:49 CST 2018
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.city
     *
     * @mbg.generated Sat Jul 28 09:38:49 CST 2018
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.name
     *
     * @mbg.generated Sat Jul 28 09:38:49 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.detailedaddress
     *
     * @mbg.generated Sat Jul 28 09:38:49 CST 2018
     */
    private String detailedaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.phone
     *
     * @mbg.generated Sat Jul 28 09:38:49 CST 2018
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.addressid
     *
     * @return the value of address.addressid
     *
     * @mbg.generated Sat Jul 28 09:38:49 CST 2018
     */
    public Integer getAddressid() {
        return addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.addressid
     *
     * @param addressid the value for address.addressid
     *
     * @mbg.generated Sat Jul 28 09:38:49 CST 2018
     */
    public void setAddressid(Integer addressid) {
        this.addressid = addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.userid
     *
     * @return the value of address.userid
     *
     * @mbg.generated Sat Jul 28 09:38:49 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.userid
     *
     * @param userid the value for address.userid
     *
     * @mbg.generated Sat Jul 28 09:38:49 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.province
     *
     * @return the value of address.province
     *
     * @mbg.generated Sat Jul 28 09:38:49 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.province
     *
     * @param province the value for address.province
     *
     * @mbg.generated Sat Jul 28 09:38:49 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.city
     *
     * @return the value of address.city
     *
     * @mbg.generated Sat Jul 28 09:38:49 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.city
     *
     * @param city the value for address.city
     *
     * @mbg.generated Sat Jul 28 09:38:49 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.name
     *
     * @return the value of address.name
     *
     * @mbg.generated Sat Jul 28 09:38:49 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.name
     *
     * @param name the value for address.name
     *
     * @mbg.generated Sat Jul 28 09:38:49 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.detailedaddress
     *
     * @return the value of address.detailedaddress
     *
     * @mbg.generated Sat Jul 28 09:38:49 CST 2018
     */
    public String getDetailedaddress() {
        return detailedaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.detailedaddress
     *
     * @param detailedaddress the value for address.detailedaddress
     *
     * @mbg.generated Sat Jul 28 09:38:49 CST 2018
     */
    public void setDetailedaddress(String detailedaddress) {
        this.detailedaddress = detailedaddress == null ? null : detailedaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.phone
     *
     * @return the value of address.phone
     *
     * @mbg.generated Sat Jul 28 09:38:49 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.phone
     *
     * @param phone the value for address.phone
     *
     * @mbg.generated Sat Jul 28 09:38:49 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
    @Override
	public String toString() {
		return "Address [addressid=" + addressid + ", userid=" + userid
				+ ", province=" + province + ", city=" + city + ", name="
				+ name + ", detailedaddress=" + detailedaddress + ", phone="
				+ phone + "]";
	}
    
}