package com.neusoft.domain;

public class Collection {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.userid
     *
     * @mbg.generated Wed Aug 01 10:59:24 CST 2018
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.productid
     *
     * @mbg.generated Wed Aug 01 10:59:24 CST 2018
     */
    private Integer productid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.userid
     *
     * @return the value of collection.userid
     *
     * @mbg.generated Wed Aug 01 10:59:24 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.userid
     *
     * @param userid the value for collection.userid
     *
     * @mbg.generated Wed Aug 01 10:59:24 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.productid
     *
     * @return the value of collection.productid
     *
     * @mbg.generated Wed Aug 01 10:59:24 CST 2018
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.productid
     *
     * @param productid the value for collection.productid
     *
     * @mbg.generated Wed Aug 01 10:59:24 CST 2018
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }
}