package com.neusoft.domain;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.userid
     *
     * @mbg.generated Thu Jul 26 20:34:49 CST 2018
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.productid
     *
     * @mbg.generated Thu Jul 26 20:34:49 CST 2018
     */
    private Integer productid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbg.generated Thu Jul 26 20:34:49 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentdate
     *
     * @mbg.generated Thu Jul 26 20:34:49 CST 2018
     */
    private String commentdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.userid
     *
     * @return the value of comment.userid
     *
     * @mbg.generated Thu Jul 26 20:34:49 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.userid
     *
     * @param userid the value for comment.userid
     *
     * @mbg.generated Thu Jul 26 20:34:49 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.productid
     *
     * @return the value of comment.productid
     *
     * @mbg.generated Thu Jul 26 20:34:49 CST 2018
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.productid
     *
     * @param productid the value for comment.productid
     *
     * @mbg.generated Thu Jul 26 20:34:49 CST 2018
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbg.generated Thu Jul 26 20:34:49 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbg.generated Thu Jul 26 20:34:49 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentdate
     *
     * @return the value of comment.commentdate
     *
     * @mbg.generated Thu Jul 26 20:34:49 CST 2018
     */
    public String getCommentdate() {
        return commentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentdate
     *
     * @param commentdate the value for comment.commentdate
     *
     * @mbg.generated Thu Jul 26 20:34:49 CST 2018
     */
    public void setCommentdate(String commentdate) {
        this.commentdate = commentdate == null ? null : commentdate.trim();
    }
}