package com.neusoft.domain;

public class Mycollection {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycollection.userid
     *
     * @mbg.generated Wed Aug 01 12:03:47 CST 2018
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycollection.productid
     *
     * @mbg.generated Wed Aug 01 12:03:47 CST 2018
     */
    private Integer productid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycollection.userid
     *
     * @return the value of mycollection.userid
     *
     * @mbg.generated Wed Aug 01 12:03:47 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycollection.userid
     *
     * @param userid the value for mycollection.userid
     *
     * @mbg.generated Wed Aug 01 12:03:47 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycollection.productid
     *
     * @return the value of mycollection.productid
     *
     * @mbg.generated Wed Aug 01 12:03:47 CST 2018
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycollection.productid
     *
     * @param productid the value for mycollection.productid
     *
     * @mbg.generated Wed Aug 01 12:03:47 CST 2018
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }
}