package com.neusoft.domain;

public class OrderContent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_content.orderid
     *
     * @mbg.generated Sun Jul 29 17:17:17 CST 2018
     */
    private Integer orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_content.productid
     *
     * @mbg.generated Sun Jul 29 17:17:17 CST 2018
     */
    private Integer productid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_content.amount
     *
     * @mbg.generated Sun Jul 29 17:17:17 CST 2018
     */
    private Integer amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_content.orderid
     *
     * @return the value of order_content.orderid
     *
     * @mbg.generated Sun Jul 29 17:17:17 CST 2018
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_content.orderid
     *
     * @param orderid the value for order_content.orderid
     *
     * @mbg.generated Sun Jul 29 17:17:17 CST 2018
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_content.productid
     *
     * @return the value of order_content.productid
     *
     * @mbg.generated Sun Jul 29 17:17:17 CST 2018
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_content.productid
     *
     * @param productid the value for order_content.productid
     *
     * @mbg.generated Sun Jul 29 17:17:17 CST 2018
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_content.amount
     *
     * @return the value of order_content.amount
     *
     * @mbg.generated Sun Jul 29 17:17:17 CST 2018
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_content.amount
     *
     * @param amount the value for order_content.amount
     *
     * @mbg.generated Sun Jul 29 17:17:17 CST 2018
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
}