package com.neusoft.domain;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.productid
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    private Integer productid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.productname
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    private String productname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    private Float price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.productdetail
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    private String productdetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.remain
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    private Integer remain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.before_p
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    private Float beforeP;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.main_picture
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    private String mainPicture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.side_picture_1
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    private String sidePicture1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.side_picture_2
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    private String sidePicture2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.side_picture_3
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    private String sidePicture3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.side_picture_4
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    private String sidePicture4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.side_picture_5
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    private String sidePicture5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.type
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.brand
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.sales
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    private Integer sales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.likenum
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    private Float likenum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productid
     *
     * @return the value of product.productid
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productid
     *
     * @param productid the value for product.productid
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productname
     *
     * @return the value of product.productname
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productname
     *
     * @param productname the value for product.productname
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    public void setProductname(String productname) {
        this.productname = productname == null ? null : productname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productdetail
     *
     * @return the value of product.productdetail
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    public String getProductdetail() {
        return productdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productdetail
     *
     * @param productdetail the value for product.productdetail
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    public void setProductdetail(String productdetail) {
        this.productdetail = productdetail == null ? null : productdetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.remain
     *
     * @return the value of product.remain
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    public Integer getRemain() {
        return remain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.remain
     *
     * @param remain the value for product.remain
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    public void setRemain(Integer remain) {
        this.remain = remain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.before_p
     *
     * @return the value of product.before_p
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    public Float getBeforeP() {
        return beforeP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.before_p
     *
     * @param beforeP the value for product.before_p
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    public void setBeforeP(Float beforeP) {
        this.beforeP = beforeP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.main_picture
     *
     * @return the value of product.main_picture
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    public String getMainPicture() {
        return mainPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.main_picture
     *
     * @param mainPicture the value for product.main_picture
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    public void setMainPicture(String mainPicture) {
        this.mainPicture = mainPicture == null ? null : mainPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.side_picture_1
     *
     * @return the value of product.side_picture_1
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    public String getSidePicture1() {
        return sidePicture1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.side_picture_1
     *
     * @param sidePicture1 the value for product.side_picture_1
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    public void setSidePicture1(String sidePicture1) {
        this.sidePicture1 = sidePicture1 == null ? null : sidePicture1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.side_picture_2
     *
     * @return the value of product.side_picture_2
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    public String getSidePicture2() {
        return sidePicture2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.side_picture_2
     *
     * @param sidePicture2 the value for product.side_picture_2
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    public void setSidePicture2(String sidePicture2) {
        this.sidePicture2 = sidePicture2 == null ? null : sidePicture2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.side_picture_3
     *
     * @return the value of product.side_picture_3
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    public String getSidePicture3() {
        return sidePicture3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.side_picture_3
     *
     * @param sidePicture3 the value for product.side_picture_3
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    public void setSidePicture3(String sidePicture3) {
        this.sidePicture3 = sidePicture3 == null ? null : sidePicture3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.side_picture_4
     *
     * @return the value of product.side_picture_4
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    public String getSidePicture4() {
        return sidePicture4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.side_picture_4
     *
     * @param sidePicture4 the value for product.side_picture_4
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    public void setSidePicture4(String sidePicture4) {
        this.sidePicture4 = sidePicture4 == null ? null : sidePicture4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.side_picture_5
     *
     * @return the value of product.side_picture_5
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    public String getSidePicture5() {
        return sidePicture5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.side_picture_5
     *
     * @param sidePicture5 the value for product.side_picture_5
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    public void setSidePicture5(String sidePicture5) {
        this.sidePicture5 = sidePicture5 == null ? null : sidePicture5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.type
     *
     * @return the value of product.type
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.type
     *
     * @param type the value for product.type
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.brand
     *
     * @return the value of product.brand
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.brand
     *
     * @param brand the value for product.brand
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sales
     *
     * @return the value of product.sales
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    public Integer getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sales
     *
     * @param sales the value for product.sales
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    public void setSales(Integer sales) {
        this.sales = sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.likenum
     *
     * @return the value of product.likenum
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    public Float getLikenum() {
        return likenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.likenum
     *
     * @param likenum the value for product.likenum
     *
     * @mbg.generated Tue Jul 31 19:25:22 CST 2018
     */
    public void setLikenum(Float likenum) {
        this.likenum = likenum;
    }


}