package com.neusoft.domain;

import java.util.ArrayList;
import java.util.List;

public class ProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public ProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProductidIsNull() {
            addCriterion("productid is null");
            return (Criteria) this;
        }

        public Criteria andProductidIsNotNull() {
            addCriterion("productid is not null");
            return (Criteria) this;
        }

        public Criteria andProductidEqualTo(Integer value) {
            addCriterion("productid =", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidNotEqualTo(Integer value) {
            addCriterion("productid <>", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidGreaterThan(Integer value) {
            addCriterion("productid >", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidGreaterThanOrEqualTo(Integer value) {
            addCriterion("productid >=", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidLessThan(Integer value) {
            addCriterion("productid <", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidLessThanOrEqualTo(Integer value) {
            addCriterion("productid <=", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidIn(List<Integer> values) {
            addCriterion("productid in", values, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidNotIn(List<Integer> values) {
            addCriterion("productid not in", values, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidBetween(Integer value1, Integer value2) {
            addCriterion("productid between", value1, value2, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidNotBetween(Integer value1, Integer value2) {
            addCriterion("productid not between", value1, value2, "productid");
            return (Criteria) this;
        }

        public Criteria andProductnameIsNull() {
            addCriterion("productname is null");
            return (Criteria) this;
        }

        public Criteria andProductnameIsNotNull() {
            addCriterion("productname is not null");
            return (Criteria) this;
        }

        public Criteria andProductnameEqualTo(String value) {
            addCriterion("productname =", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameNotEqualTo(String value) {
            addCriterion("productname <>", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameGreaterThan(String value) {
            addCriterion("productname >", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameGreaterThanOrEqualTo(String value) {
            addCriterion("productname >=", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameLessThan(String value) {
            addCriterion("productname <", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameLessThanOrEqualTo(String value) {
            addCriterion("productname <=", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameLike(String value) {
            addCriterion("productname like", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameNotLike(String value) {
            addCriterion("productname not like", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameIn(List<String> values) {
            addCriterion("productname in", values, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameNotIn(List<String> values) {
            addCriterion("productname not in", values, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameBetween(String value1, String value2) {
            addCriterion("productname between", value1, value2, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameNotBetween(String value1, String value2) {
            addCriterion("productname not between", value1, value2, "productname");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Double value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Double value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Double value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Double value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Double value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Double> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Double> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Double value1, Double value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Double value1, Double value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andProductdetailIsNull() {
            addCriterion("productdetail is null");
            return (Criteria) this;
        }

        public Criteria andProductdetailIsNotNull() {
            addCriterion("productdetail is not null");
            return (Criteria) this;
        }

        public Criteria andProductdetailEqualTo(String value) {
            addCriterion("productdetail =", value, "productdetail");
            return (Criteria) this;
        }

        public Criteria andProductdetailNotEqualTo(String value) {
            addCriterion("productdetail <>", value, "productdetail");
            return (Criteria) this;
        }

        public Criteria andProductdetailGreaterThan(String value) {
            addCriterion("productdetail >", value, "productdetail");
            return (Criteria) this;
        }

        public Criteria andProductdetailGreaterThanOrEqualTo(String value) {
            addCriterion("productdetail >=", value, "productdetail");
            return (Criteria) this;
        }

        public Criteria andProductdetailLessThan(String value) {
            addCriterion("productdetail <", value, "productdetail");
            return (Criteria) this;
        }

        public Criteria andProductdetailLessThanOrEqualTo(String value) {
            addCriterion("productdetail <=", value, "productdetail");
            return (Criteria) this;
        }

        public Criteria andProductdetailLike(String value) {
            addCriterion("productdetail like", value, "productdetail");
            return (Criteria) this;
        }

        public Criteria andProductdetailNotLike(String value) {
            addCriterion("productdetail not like", value, "productdetail");
            return (Criteria) this;
        }

        public Criteria andProductdetailIn(List<String> values) {
            addCriterion("productdetail in", values, "productdetail");
            return (Criteria) this;
        }

        public Criteria andProductdetailNotIn(List<String> values) {
            addCriterion("productdetail not in", values, "productdetail");
            return (Criteria) this;
        }

        public Criteria andProductdetailBetween(String value1, String value2) {
            addCriterion("productdetail between", value1, value2, "productdetail");
            return (Criteria) this;
        }

        public Criteria andProductdetailNotBetween(String value1, String value2) {
            addCriterion("productdetail not between", value1, value2, "productdetail");
            return (Criteria) this;
        }

        public Criteria andRemainIsNull() {
            addCriterion("remain is null");
            return (Criteria) this;
        }

        public Criteria andRemainIsNotNull() {
            addCriterion("remain is not null");
            return (Criteria) this;
        }

        public Criteria andRemainEqualTo(Integer value) {
            addCriterion("remain =", value, "remain");
            return (Criteria) this;
        }

        public Criteria andRemainNotEqualTo(Integer value) {
            addCriterion("remain <>", value, "remain");
            return (Criteria) this;
        }

        public Criteria andRemainGreaterThan(Integer value) {
            addCriterion("remain >", value, "remain");
            return (Criteria) this;
        }

        public Criteria andRemainGreaterThanOrEqualTo(Integer value) {
            addCriterion("remain >=", value, "remain");
            return (Criteria) this;
        }

        public Criteria andRemainLessThan(Integer value) {
            addCriterion("remain <", value, "remain");
            return (Criteria) this;
        }

        public Criteria andRemainLessThanOrEqualTo(Integer value) {
            addCriterion("remain <=", value, "remain");
            return (Criteria) this;
        }

        public Criteria andRemainIn(List<Integer> values) {
            addCriterion("remain in", values, "remain");
            return (Criteria) this;
        }

        public Criteria andRemainNotIn(List<Integer> values) {
            addCriterion("remain not in", values, "remain");
            return (Criteria) this;
        }

        public Criteria andRemainBetween(Integer value1, Integer value2) {
            addCriterion("remain between", value1, value2, "remain");
            return (Criteria) this;
        }

        public Criteria andRemainNotBetween(Integer value1, Integer value2) {
            addCriterion("remain not between", value1, value2, "remain");
            return (Criteria) this;
        }

        public Criteria andBeforePIsNull() {
            addCriterion("before_p is null");
            return (Criteria) this;
        }

        public Criteria andBeforePIsNotNull() {
            addCriterion("before_p is not null");
            return (Criteria) this;
        }

        public Criteria andBeforePEqualTo(Integer value) {
            addCriterion("before_p =", value, "beforeP");
            return (Criteria) this;
        }

        public Criteria andBeforePNotEqualTo(Integer value) {
            addCriterion("before_p <>", value, "beforeP");
            return (Criteria) this;
        }

        public Criteria andBeforePGreaterThan(Integer value) {
            addCriterion("before_p >", value, "beforeP");
            return (Criteria) this;
        }

        public Criteria andBeforePGreaterThanOrEqualTo(Integer value) {
            addCriterion("before_p >=", value, "beforeP");
            return (Criteria) this;
        }

        public Criteria andBeforePLessThan(Integer value) {
            addCriterion("before_p <", value, "beforeP");
            return (Criteria) this;
        }

        public Criteria andBeforePLessThanOrEqualTo(Integer value) {
            addCriterion("before_p <=", value, "beforeP");
            return (Criteria) this;
        }

        public Criteria andBeforePIn(List<Integer> values) {
            addCriterion("before_p in", values, "beforeP");
            return (Criteria) this;
        }

        public Criteria andBeforePNotIn(List<Integer> values) {
            addCriterion("before_p not in", values, "beforeP");
            return (Criteria) this;
        }

        public Criteria andBeforePBetween(Integer value1, Integer value2) {
            addCriterion("before_p between", value1, value2, "beforeP");
            return (Criteria) this;
        }

        public Criteria andBeforePNotBetween(Integer value1, Integer value2) {
            addCriterion("before_p not between", value1, value2, "beforeP");
            return (Criteria) this;
        }

        public Criteria andMainPictureIsNull() {
            addCriterion("main_picture is null");
            return (Criteria) this;
        }

        public Criteria andMainPictureIsNotNull() {
            addCriterion("main_picture is not null");
            return (Criteria) this;
        }

        public Criteria andMainPictureEqualTo(String value) {
            addCriterion("main_picture =", value, "mainPicture");
            return (Criteria) this;
        }

        public Criteria andMainPictureNotEqualTo(String value) {
            addCriterion("main_picture <>", value, "mainPicture");
            return (Criteria) this;
        }

        public Criteria andMainPictureGreaterThan(String value) {
            addCriterion("main_picture >", value, "mainPicture");
            return (Criteria) this;
        }

        public Criteria andMainPictureGreaterThanOrEqualTo(String value) {
            addCriterion("main_picture >=", value, "mainPicture");
            return (Criteria) this;
        }

        public Criteria andMainPictureLessThan(String value) {
            addCriterion("main_picture <", value, "mainPicture");
            return (Criteria) this;
        }

        public Criteria andMainPictureLessThanOrEqualTo(String value) {
            addCriterion("main_picture <=", value, "mainPicture");
            return (Criteria) this;
        }

        public Criteria andMainPictureLike(String value) {
            addCriterion("main_picture like", value, "mainPicture");
            return (Criteria) this;
        }

        public Criteria andMainPictureNotLike(String value) {
            addCriterion("main_picture not like", value, "mainPicture");
            return (Criteria) this;
        }

        public Criteria andMainPictureIn(List<String> values) {
            addCriterion("main_picture in", values, "mainPicture");
            return (Criteria) this;
        }

        public Criteria andMainPictureNotIn(List<String> values) {
            addCriterion("main_picture not in", values, "mainPicture");
            return (Criteria) this;
        }

        public Criteria andMainPictureBetween(String value1, String value2) {
            addCriterion("main_picture between", value1, value2, "mainPicture");
            return (Criteria) this;
        }

        public Criteria andMainPictureNotBetween(String value1, String value2) {
            addCriterion("main_picture not between", value1, value2, "mainPicture");
            return (Criteria) this;
        }

        public Criteria andSidePicture1IsNull() {
            addCriterion("side_picture_1 is null");
            return (Criteria) this;
        }

        public Criteria andSidePicture1IsNotNull() {
            addCriterion("side_picture_1 is not null");
            return (Criteria) this;
        }

        public Criteria andSidePicture1EqualTo(String value) {
            addCriterion("side_picture_1 =", value, "sidePicture1");
            return (Criteria) this;
        }

        public Criteria andSidePicture1NotEqualTo(String value) {
            addCriterion("side_picture_1 <>", value, "sidePicture1");
            return (Criteria) this;
        }

        public Criteria andSidePicture1GreaterThan(String value) {
            addCriterion("side_picture_1 >", value, "sidePicture1");
            return (Criteria) this;
        }

        public Criteria andSidePicture1GreaterThanOrEqualTo(String value) {
            addCriterion("side_picture_1 >=", value, "sidePicture1");
            return (Criteria) this;
        }

        public Criteria andSidePicture1LessThan(String value) {
            addCriterion("side_picture_1 <", value, "sidePicture1");
            return (Criteria) this;
        }

        public Criteria andSidePicture1LessThanOrEqualTo(String value) {
            addCriterion("side_picture_1 <=", value, "sidePicture1");
            return (Criteria) this;
        }

        public Criteria andSidePicture1Like(String value) {
            addCriterion("side_picture_1 like", value, "sidePicture1");
            return (Criteria) this;
        }

        public Criteria andSidePicture1NotLike(String value) {
            addCriterion("side_picture_1 not like", value, "sidePicture1");
            return (Criteria) this;
        }

        public Criteria andSidePicture1In(List<String> values) {
            addCriterion("side_picture_1 in", values, "sidePicture1");
            return (Criteria) this;
        }

        public Criteria andSidePicture1NotIn(List<String> values) {
            addCriterion("side_picture_1 not in", values, "sidePicture1");
            return (Criteria) this;
        }

        public Criteria andSidePicture1Between(String value1, String value2) {
            addCriterion("side_picture_1 between", value1, value2, "sidePicture1");
            return (Criteria) this;
        }

        public Criteria andSidePicture1NotBetween(String value1, String value2) {
            addCriterion("side_picture_1 not between", value1, value2, "sidePicture1");
            return (Criteria) this;
        }

        public Criteria andSidePicture2IsNull() {
            addCriterion("side_picture_2 is null");
            return (Criteria) this;
        }

        public Criteria andSidePicture2IsNotNull() {
            addCriterion("side_picture_2 is not null");
            return (Criteria) this;
        }

        public Criteria andSidePicture2EqualTo(String value) {
            addCriterion("side_picture_2 =", value, "sidePicture2");
            return (Criteria) this;
        }

        public Criteria andSidePicture2NotEqualTo(String value) {
            addCriterion("side_picture_2 <>", value, "sidePicture2");
            return (Criteria) this;
        }

        public Criteria andSidePicture2GreaterThan(String value) {
            addCriterion("side_picture_2 >", value, "sidePicture2");
            return (Criteria) this;
        }

        public Criteria andSidePicture2GreaterThanOrEqualTo(String value) {
            addCriterion("side_picture_2 >=", value, "sidePicture2");
            return (Criteria) this;
        }

        public Criteria andSidePicture2LessThan(String value) {
            addCriterion("side_picture_2 <", value, "sidePicture2");
            return (Criteria) this;
        }

        public Criteria andSidePicture2LessThanOrEqualTo(String value) {
            addCriterion("side_picture_2 <=", value, "sidePicture2");
            return (Criteria) this;
        }

        public Criteria andSidePicture2Like(String value) {
            addCriterion("side_picture_2 like", value, "sidePicture2");
            return (Criteria) this;
        }

        public Criteria andSidePicture2NotLike(String value) {
            addCriterion("side_picture_2 not like", value, "sidePicture2");
            return (Criteria) this;
        }

        public Criteria andSidePicture2In(List<String> values) {
            addCriterion("side_picture_2 in", values, "sidePicture2");
            return (Criteria) this;
        }

        public Criteria andSidePicture2NotIn(List<String> values) {
            addCriterion("side_picture_2 not in", values, "sidePicture2");
            return (Criteria) this;
        }

        public Criteria andSidePicture2Between(String value1, String value2) {
            addCriterion("side_picture_2 between", value1, value2, "sidePicture2");
            return (Criteria) this;
        }

        public Criteria andSidePicture2NotBetween(String value1, String value2) {
            addCriterion("side_picture_2 not between", value1, value2, "sidePicture2");
            return (Criteria) this;
        }

        public Criteria andSidePicture3IsNull() {
            addCriterion("side_picture_3 is null");
            return (Criteria) this;
        }

        public Criteria andSidePicture3IsNotNull() {
            addCriterion("side_picture_3 is not null");
            return (Criteria) this;
        }

        public Criteria andSidePicture3EqualTo(String value) {
            addCriterion("side_picture_3 =", value, "sidePicture3");
            return (Criteria) this;
        }

        public Criteria andSidePicture3NotEqualTo(String value) {
            addCriterion("side_picture_3 <>", value, "sidePicture3");
            return (Criteria) this;
        }

        public Criteria andSidePicture3GreaterThan(String value) {
            addCriterion("side_picture_3 >", value, "sidePicture3");
            return (Criteria) this;
        }

        public Criteria andSidePicture3GreaterThanOrEqualTo(String value) {
            addCriterion("side_picture_3 >=", value, "sidePicture3");
            return (Criteria) this;
        }

        public Criteria andSidePicture3LessThan(String value) {
            addCriterion("side_picture_3 <", value, "sidePicture3");
            return (Criteria) this;
        }

        public Criteria andSidePicture3LessThanOrEqualTo(String value) {
            addCriterion("side_picture_3 <=", value, "sidePicture3");
            return (Criteria) this;
        }

        public Criteria andSidePicture3Like(String value) {
            addCriterion("side_picture_3 like", value, "sidePicture3");
            return (Criteria) this;
        }

        public Criteria andSidePicture3NotLike(String value) {
            addCriterion("side_picture_3 not like", value, "sidePicture3");
            return (Criteria) this;
        }

        public Criteria andSidePicture3In(List<String> values) {
            addCriterion("side_picture_3 in", values, "sidePicture3");
            return (Criteria) this;
        }

        public Criteria andSidePicture3NotIn(List<String> values) {
            addCriterion("side_picture_3 not in", values, "sidePicture3");
            return (Criteria) this;
        }

        public Criteria andSidePicture3Between(String value1, String value2) {
            addCriterion("side_picture_3 between", value1, value2, "sidePicture3");
            return (Criteria) this;
        }

        public Criteria andSidePicture3NotBetween(String value1, String value2) {
            addCriterion("side_picture_3 not between", value1, value2, "sidePicture3");
            return (Criteria) this;
        }

        public Criteria andSidePicture4IsNull() {
            addCriterion("side_picture_4 is null");
            return (Criteria) this;
        }

        public Criteria andSidePicture4IsNotNull() {
            addCriterion("side_picture_4 is not null");
            return (Criteria) this;
        }

        public Criteria andSidePicture4EqualTo(String value) {
            addCriterion("side_picture_4 =", value, "sidePicture4");
            return (Criteria) this;
        }

        public Criteria andSidePicture4NotEqualTo(String value) {
            addCriterion("side_picture_4 <>", value, "sidePicture4");
            return (Criteria) this;
        }

        public Criteria andSidePicture4GreaterThan(String value) {
            addCriterion("side_picture_4 >", value, "sidePicture4");
            return (Criteria) this;
        }

        public Criteria andSidePicture4GreaterThanOrEqualTo(String value) {
            addCriterion("side_picture_4 >=", value, "sidePicture4");
            return (Criteria) this;
        }

        public Criteria andSidePicture4LessThan(String value) {
            addCriterion("side_picture_4 <", value, "sidePicture4");
            return (Criteria) this;
        }

        public Criteria andSidePicture4LessThanOrEqualTo(String value) {
            addCriterion("side_picture_4 <=", value, "sidePicture4");
            return (Criteria) this;
        }

        public Criteria andSidePicture4Like(String value) {
            addCriterion("side_picture_4 like", value, "sidePicture4");
            return (Criteria) this;
        }

        public Criteria andSidePicture4NotLike(String value) {
            addCriterion("side_picture_4 not like", value, "sidePicture4");
            return (Criteria) this;
        }

        public Criteria andSidePicture4In(List<String> values) {
            addCriterion("side_picture_4 in", values, "sidePicture4");
            return (Criteria) this;
        }

        public Criteria andSidePicture4NotIn(List<String> values) {
            addCriterion("side_picture_4 not in", values, "sidePicture4");
            return (Criteria) this;
        }

        public Criteria andSidePicture4Between(String value1, String value2) {
            addCriterion("side_picture_4 between", value1, value2, "sidePicture4");
            return (Criteria) this;
        }

        public Criteria andSidePicture4NotBetween(String value1, String value2) {
            addCriterion("side_picture_4 not between", value1, value2, "sidePicture4");
            return (Criteria) this;
        }

        public Criteria andSidePicture5IsNull() {
            addCriterion("side_picture_5 is null");
            return (Criteria) this;
        }

        public Criteria andSidePicture5IsNotNull() {
            addCriterion("side_picture_5 is not null");
            return (Criteria) this;
        }

        public Criteria andSidePicture5EqualTo(String value) {
            addCriterion("side_picture_5 =", value, "sidePicture5");
            return (Criteria) this;
        }

        public Criteria andSidePicture5NotEqualTo(String value) {
            addCriterion("side_picture_5 <>", value, "sidePicture5");
            return (Criteria) this;
        }

        public Criteria andSidePicture5GreaterThan(String value) {
            addCriterion("side_picture_5 >", value, "sidePicture5");
            return (Criteria) this;
        }

        public Criteria andSidePicture5GreaterThanOrEqualTo(String value) {
            addCriterion("side_picture_5 >=", value, "sidePicture5");
            return (Criteria) this;
        }

        public Criteria andSidePicture5LessThan(String value) {
            addCriterion("side_picture_5 <", value, "sidePicture5");
            return (Criteria) this;
        }

        public Criteria andSidePicture5LessThanOrEqualTo(String value) {
            addCriterion("side_picture_5 <=", value, "sidePicture5");
            return (Criteria) this;
        }

        public Criteria andSidePicture5Like(String value) {
            addCriterion("side_picture_5 like", value, "sidePicture5");
            return (Criteria) this;
        }

        public Criteria andSidePicture5NotLike(String value) {
            addCriterion("side_picture_5 not like", value, "sidePicture5");
            return (Criteria) this;
        }

        public Criteria andSidePicture5In(List<String> values) {
            addCriterion("side_picture_5 in", values, "sidePicture5");
            return (Criteria) this;
        }

        public Criteria andSidePicture5NotIn(List<String> values) {
            addCriterion("side_picture_5 not in", values, "sidePicture5");
            return (Criteria) this;
        }

        public Criteria andSidePicture5Between(String value1, String value2) {
            addCriterion("side_picture_5 between", value1, value2, "sidePicture5");
            return (Criteria) this;
        }

        public Criteria andSidePicture5NotBetween(String value1, String value2) {
            addCriterion("side_picture_5 not between", value1, value2, "sidePicture5");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated do_not_delete_during_merge Fri Jul 27 21:57:31 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}