package com.neusoft.domain;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.productid
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    private Integer productid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.productname
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    private String productname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.productdetail
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    private String productdetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.remain
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    private Integer remain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.before_p
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    private Integer beforeP;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.main_picture
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    private String mainPicture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.side_picture_1
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    private String sidePicture1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.side_picture_2
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    private String sidePicture2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.side_picture_3
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    private String sidePicture3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.side_picture_4
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    private String sidePicture4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.side_picture_5
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    private String sidePicture5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productid
     *
     * @return the value of product.productid
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productid
     *
     * @param productid the value for product.productid
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productname
     *
     * @return the value of product.productname
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productname
     *
     * @param productname the value for product.productname
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public void setProductname(String productname) {
        this.productname = productname == null ? null : productname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productdetail
     *
     * @return the value of product.productdetail
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public String getProductdetail() {
        return productdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productdetail
     *
     * @param productdetail the value for product.productdetail
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public void setProductdetail(String productdetail) {
        this.productdetail = productdetail == null ? null : productdetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.remain
     *
     * @return the value of product.remain
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public Integer getRemain() {
        return remain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.remain
     *
     * @param remain the value for product.remain
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public void setRemain(Integer remain) {
        this.remain = remain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.before_p
     *
     * @return the value of product.before_p
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public Integer getBeforeP() {
        return beforeP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.before_p
     *
     * @param beforeP the value for product.before_p
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public void setBeforeP(Integer beforeP) {
        this.beforeP = beforeP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.main_picture
     *
     * @return the value of product.main_picture
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public String getMainPicture() {
        return mainPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.main_picture
     *
     * @param mainPicture the value for product.main_picture
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public void setMainPicture(String mainPicture) {
        this.mainPicture = mainPicture == null ? null : mainPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.side_picture_1
     *
     * @return the value of product.side_picture_1
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public String getSidePicture1() {
        return sidePicture1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.side_picture_1
     *
     * @param sidePicture1 the value for product.side_picture_1
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public void setSidePicture1(String sidePicture1) {
        this.sidePicture1 = sidePicture1 == null ? null : sidePicture1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.side_picture_2
     *
     * @return the value of product.side_picture_2
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public String getSidePicture2() {
        return sidePicture2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.side_picture_2
     *
     * @param sidePicture2 the value for product.side_picture_2
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public void setSidePicture2(String sidePicture2) {
        this.sidePicture2 = sidePicture2 == null ? null : sidePicture2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.side_picture_3
     *
     * @return the value of product.side_picture_3
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public String getSidePicture3() {
        return sidePicture3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.side_picture_3
     *
     * @param sidePicture3 the value for product.side_picture_3
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public void setSidePicture3(String sidePicture3) {
        this.sidePicture3 = sidePicture3 == null ? null : sidePicture3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.side_picture_4
     *
     * @return the value of product.side_picture_4
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public String getSidePicture4() {
        return sidePicture4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.side_picture_4
     *
     * @param sidePicture4 the value for product.side_picture_4
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public void setSidePicture4(String sidePicture4) {
        this.sidePicture4 = sidePicture4 == null ? null : sidePicture4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.side_picture_5
     *
     * @return the value of product.side_picture_5
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public String getSidePicture5() {
        return sidePicture5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.side_picture_5
     *
     * @param sidePicture5 the value for product.side_picture_5
     *
     * @mbg.generated Fri Jul 27 21:57:31 CST 2018
     */
    public void setSidePicture5(String sidePicture5) {
        this.sidePicture5 = sidePicture5 == null ? null : sidePicture5.trim();
    }
}