package com.neusoft.domain;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.productid
     *
     * @mbg.generated Thu Jul 26 20:34:49 CST 2018
     */
    private Integer productid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.productname
     *
     * @mbg.generated Thu Jul 26 20:34:49 CST 2018
     */
    private String productname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbg.generated Thu Jul 26 20:34:49 CST 2018
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.productdetail
     *
     * @mbg.generated Thu Jul 26 20:34:49 CST 2018
     */
    private String productdetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.remain
     *
     * @mbg.generated Thu Jul 26 20:34:49 CST 2018
     */
    private Integer remain;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productid
     *
     * @return the value of product.productid
     *
     * @mbg.generated Thu Jul 26 20:34:49 CST 2018
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productid
     *
     * @param productid the value for product.productid
     *
     * @mbg.generated Thu Jul 26 20:34:49 CST 2018
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productname
     *
     * @return the value of product.productname
     *
     * @mbg.generated Thu Jul 26 20:34:49 CST 2018
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productname
     *
     * @param productname the value for product.productname
     *
     * @mbg.generated Thu Jul 26 20:34:49 CST 2018
     */
    public void setProductname(String productname) {
        this.productname = productname == null ? null : productname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbg.generated Thu Jul 26 20:34:49 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbg.generated Thu Jul 26 20:34:49 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productdetail
     *
     * @return the value of product.productdetail
     *
     * @mbg.generated Thu Jul 26 20:34:49 CST 2018
     */
    public String getProductdetail() {
        return productdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productdetail
     *
     * @param productdetail the value for product.productdetail
     *
     * @mbg.generated Thu Jul 26 20:34:49 CST 2018
     */
    public void setProductdetail(String productdetail) {
        this.productdetail = productdetail == null ? null : productdetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.remain
     *
     * @return the value of product.remain
     *
     * @mbg.generated Thu Jul 26 20:34:49 CST 2018
     */
    public Integer getRemain() {
        return remain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.remain
     *
     * @param remain the value for product.remain
     *
     * @mbg.generated Thu Jul 26 20:34:49 CST 2018
     */
    public void setRemain(Integer remain) {
        this.remain = remain;
    }
}