package com.neusoft.domain;

public class Shoppingcar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcar.userid
     *
     * @mbg.generated Sat Jul 28 15:46:30 CST 2018
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcar.productid
     *
     * @mbg.generated Sat Jul 28 15:46:30 CST 2018
     */
    private Integer productid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcar.amount
     *
     * @mbg.generated Sat Jul 28 15:46:30 CST 2018
     */
    private Integer amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcar.userid
     *
     * @return the value of shoppingcar.userid
     *
     * @mbg.generated Sat Jul 28 15:46:30 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcar.userid
     *
     * @param userid the value for shoppingcar.userid
     *
     * @mbg.generated Sat Jul 28 15:46:30 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcar.productid
     *
     * @return the value of shoppingcar.productid
     *
     * @mbg.generated Sat Jul 28 15:46:30 CST 2018
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcar.productid
     *
     * @param productid the value for shoppingcar.productid
     *
     * @mbg.generated Sat Jul 28 15:46:30 CST 2018
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcar.amount
     *
     * @return the value of shoppingcar.amount
     *
     * @mbg.generated Sat Jul 28 15:46:30 CST 2018
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcar.amount
     *
     * @param amount the value for shoppingcar.amount
     *
     * @mbg.generated Sat Jul 28 15:46:30 CST 2018
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
}