package com.neusoft.dao;

import com.neusoft.domain.Shoppingcar;
import com.neusoft.domain.ShoppingcarExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShoppingcarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcar
     *
     * @mbg.generated Sat Jul 28 15:46:30 CST 2018
     */
    long countByExample(ShoppingcarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcar
     *
     * @mbg.generated Sat Jul 28 15:46:30 CST 2018
     */
    int deleteByExample(ShoppingcarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcar
     *
     * @mbg.generated Sat Jul 28 15:46:30 CST 2018
     */
    int insert(Shoppingcar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcar
     *
     * @mbg.generated Sat Jul 28 15:46:30 CST 2018
     */
    int insertSelective(Shoppingcar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcar
     *
     * @mbg.generated Sat Jul 28 15:46:30 CST 2018
     */
    List<Shoppingcar> selectByExample(ShoppingcarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcar
     *
     * @mbg.generated Sat Jul 28 15:46:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") Shoppingcar record, @Param("example") ShoppingcarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcar
     *
     * @mbg.generated Sat Jul 28 15:46:30 CST 2018
     */
    int updateByExample(@Param("record") Shoppingcar record, @Param("example") ShoppingcarExample example);
}